extends:
  - airbnb-base
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier

plugins:
  - import
  - mocha
  - chai-friendly
  - prettier

env:
  mocha: true

globals:
  should: false

rules:
  comma-dangle: 0
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  indent: 2
  eol-last: 2
  quotes:
    - 2
    - single
  prettier/prettier:
    - 2
    - singleQuote: true