apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-comment-manager
  description: Component for github-comment-manager
  annotations:
    circleci.com/project-slug: github/newsuk/github-comment-manager
    backstage.io/source-location: url:https://github.com/newsuk/github-comment-manager/
    github.com/team-slug: newsuk/github-comment-manager
    backstage.io/productivity-hub-metrics-enabled: 'true'
  tags:
    - bu:newsuk
spec:
  type: service
  lifecycle: production
  owner: nuk